### ISSUE TITLE
v0.5.1 release file is broken

### ISSUE THREAD

**Issue by compliment** [robrotheram/gogallery#13]
Hey there, 
 It's not a problem but https://github.com/robrotheram/gogallery/releases/tag/v0.5.1 tar file is broken, you can replace it.

**Comment by robrotheram** [comment]
Hello, Sorry about the release being broken. I have created a new release https://github.com/robrotheram/gogallery/releases/tag/v0.6 contains a few bug fixes dependency updates and the gallery title is now customizable in the UI
