### ISSUE TITLE
Create a flatpak 

### ISSUE THREAD

**Issue by robrotheram** [robrotheram/gogallery#48]
The repository already contains A docker file need to package the binary as a flatpak for Linux distribution 
main requirements is libvips to be installed. 

Unsure if we need to include webkit or if wails.io handles that in the compiling of the binary

**Comment by semi-infiknight** [comment]
can u assign me this issue

**Comment by semi-infiknight** [comment]
please

**Comment by robrotheram** [comment]
Sure go right ahead

**Comment by robrotheram** [comment]
Closing issue flatpak support is now in its own repo: https://github.com/robrotheram/io.exceptionerror.gogallery
