### ISSUE TITLE
Is this going to be hard to run on Windows?

### ISSUE THREAD

**Issue by tyeeman** [robrotheram/gogallery#50]
I don't have "make" and there is no exe for Windows so...should I not bother?

**Comment by robrotheram** [comment]
Hi I looked into cross compiling a windows build but looks like there is a bug in the image converting library that is being used
https://github.com/h2non/bimg/issues/362 which is a shame. 

It might work in WSL

**Comment by robrotheram** [comment]
Fixed in 6.0.1
