### ISSUE TITLE
Incorrectly loads images after the last one.

### ISSUE THREAD

**Issue by endokai** [robrotheram/gogallery#58]
Version: gogallery v5.4
Using browser: Chrome v120
Found two places where continuing on to the next image even after the last image caused an error.
1. On the home page (/), after loading the last photo using the mouse wheel, it is possible to continue scrolling indefinitely, resulting in a loading error with the text "undefined" being added with each scroll.
2. On the single-image view page (/photo/***), when viewing the last image, using the right arrow key on the keyboard results in continuing to open a non-existent  path (/photo/), returning a 404 or 403 (by server setting). The right arrow button on the page is hidden when the last image is loaded, so the page displays without a problem. But there is a problem with the keyboard handling.

**Comment by robrotheram** [comment]
Thanks for the bug report this has now been fixed in v6.0.1
